
markdown: kramdown

kramdown:
  input: GFM

title: TeXnikum

email-list: <span class="email-list"><span class="strikethrough">hemmelig@adresse.dk</span> (slå javascript til for at se den rigtige)</span>
email-admin: <span class="email-admin"><span class="strikethrough">hemmelig-admin@adresse.dk</span> (slå javascript til for at se den rigtige)</span>
